import type { TreeDocument } from "./types";

export const SAMPLE_TREE_ID = "sample-al-falah";

export function sampleAlFalah(): TreeDocument {
  return {
    version: 1,
    name: "Keluarga Al-Falah",
    description:
      "Contoh silsilah empat generasi dari pesantren di pesisir utara Jawa. Ubah, ganti foto, atau jadikan milikmu.",
    people: [
      {
        id: "p_ahmad",
        name: "Ahmad Al-Falah",
        gender: "male",
        title: "Kyai",
        birthYear: "1920",
        deathYear: "1998",
        birthPlace: "Demak",
        icon: "book",
        color: "navy",
        notes:
          "Pendiri pesantren Al-Falah. Dikenal merangkai nasab santri dengan teliti, malam Jumat biasanya mengaji Silsilah.",
      },
      {
        id: "p_aminah",
        name: "Siti Aminah",
        gender: "female",
        title: "Nyai",
        birthYear: "1924",
        deathYear: "2003",
        birthPlace: "Kudus",
        icon: "leaf",
        color: "lilac",
        notes: "Pengasuh pondok putri. Menjaga silsilah dari pihak ibu yang sering terlewat.",
      },
      {
        id: "p_hasan",
        name: "Hasan Al-Falah",
        gender: "male",
        birthYear: "1948",
        birthPlace: "Demak",
        icon: "landmark",
        color: "mint",
        notes: "Anak sulung. Melanjutkan pengajian dan mencatat cabang keluarga di luar pulau.",
      },
      {
        id: "p_aisyah",
        name: "Aisyah Putri",
        gender: "female",
        birthYear: "1950",
        birthPlace: "Pekalongan",
        icon: "heart",
        color: "pink",
        notes: "Menikah ke dalam keluarga Al-Falah tahun 1972. Pengrajin batik tulis.",
      },
      {
        id: "p_fatimah",
        name: "Fatimah Al-Falah",
        gender: "female",
        birthYear: "1952",
        deathYear: "2019",
        birthPlace: "Demak",
        icon: "sun",
        color: "coral",
        notes: "Guru madrasah. Cabang Darmawan bertemu di sini.",
      },
      {
        id: "p_ibrahim",
        name: "Ibrahim Darmawan",
        gender: "male",
        birthYear: "1950",
        birthPlace: "Semarang",
        icon: "shield",
        color: "cream",
        notes: "Pedagang kayu jati. Membawa cabang Semarang ke pohon ini.",
      },
      {
        id: "p_yusuf",
        name: "Yusuf Al-Falah",
        gender: "male",
        birthYear: "1955",
        birthPlace: "Demak",
        icon: "feather",
        color: "mint",
        notes: "Penyusun catatan nasab generasi ketiga. Sering menandai orang dengan ikon, bukan foto.",
      },
      {
        id: "p_maryam",
        name: "Maryam Zahro",
        gender: "female",
        birthYear: "1958",
        birthPlace: "Jepara",
        icon: "moon",
        color: "pink",
        notes: "Pengukir ukiran Jepara. Rumahnya jadi tempat kumpul lebaran.",
      },
      {
        id: "p_rayyan",
        name: "Rayyan Al-Falah",
        gender: "male",
        birthYear: "1976",
        birthPlace: "Demak",
        icon: "star",
        color: "lime",
        notes: "Arsiparis keluarga. Memindahkan silsilah dari buku tulis ke kanvas digital.",
      },
      {
        id: "p_laila",
        name: "Laila Sari",
        gender: "female",
        birthYear: "1978",
        birthPlace: "Yogyakarta",
        icon: "heart",
        color: "pink",
        notes: "Fotografer. Banyak potret di pohon ini hasil jepretannya.",
      },
      {
        id: "p_nadia",
        name: "Nadia Al-Falah",
        gender: "female",
        birthYear: "1978",
        birthPlace: "Demak",
        icon: "flag",
        color: "lilac",
        notes: "Peneliti sejarah lisan. Cabang yang belum berpasangan tetap dicatat.",
      },
      {
        id: "p_zahra",
        name: "Zahra Darmawan",
        gender: "female",
        birthYear: "1980",
        birthPlace: "Semarang",
        icon: "leaf",
        color: "mint",
        notes: "Dokter. Menikah ke keluarga Pratama.",
      },
      {
        id: "p_fajar",
        name: "Fajar Darmawan",
        gender: "male",
        birthYear: "1983",
        birthPlace: "Semarang",
        icon: "sun",
        color: "cream",
        notes: "Arsitek. Belum menikah pada catatan ini.",
      },
      {
        id: "p_hana",
        name: "Hana Al-Falah",
        gender: "female",
        birthYear: "1985",
        birthPlace: "Jepara",
        icon: "book",
        color: "coral",
        notes: "Penulis. Menyusun keterangan orang-orang di pohon ini.",
      },
      {
        id: "p_andi",
        name: "Andi Pratama",
        gender: "male",
        birthYear: "1979",
        birthPlace: "Solo",
        icon: "landmark",
        color: "navy",
        notes: "Pasangan Zahra. Membawa cabang Solo.",
      },
      {
        id: "p_adam",
        name: "Adam Al-Falah",
        gender: "male",
        birthYear: "2004",
        birthPlace: "Jakarta",
        icon: "user",
        color: "lime",
        notes: "Generasi keempat. Nasab: Adam bin Rayyan bin Hasan bin Ahmad Al-Falah.",
      },
      {
        id: "p_sofia",
        name: "Sofia Al-Falah",
        gender: "female",
        birthYear: "2007",
        birthPlace: "Jakarta",
        icon: "star",
        color: "pink",
        notes: "Adik Adam. Suka menandai orang dengan warna lilac.",
      },
      {
        id: "p_malik",
        name: "Malik Pratama",
        gender: "male",
        birthYear: "2008",
        birthPlace: "Solo",
        icon: "shield",
        color: "mint",
        notes: "Anak Zahra dan Andi. Titik temu cabang Darmawan dan Pratama.",
      },
    ],
    unions: [
      {
        id: "u_ahmad",
        a: "p_ahmad",
        b: "p_aminah",
        children: ["p_hasan", "p_fatimah", "p_yusuf"],
        label: "1946",
        notes: "Menikah di Demak setelah Kyai Ahmad selesai mondok.",
      },
      {
        id: "u_hasan",
        a: "p_hasan",
        b: "p_aisyah",
        children: ["p_rayyan", "p_nadia"],
        label: "1972",
      },
      {
        id: "u_fatimah",
        a: "p_fatimah",
        b: "p_ibrahim",
        children: ["p_zahra", "p_fajar"],
        label: "1974",
      },
      {
        id: "u_yusuf",
        a: "p_yusuf",
        b: "p_maryam",
        children: ["p_hana"],
        label: "1981",
      },
      {
        id: "u_rayyan",
        a: "p_rayyan",
        b: "p_laila",
        children: ["p_adam", "p_sofia"],
        label: "2001",
      },
      {
        id: "u_zahra",
        a: "p_zahra",
        b: "p_andi",
        children: ["p_malik"],
        label: "2005",
      },
    ],
  };
}
